version: '3.8'

services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
    depends_on:
      - prometheus

  zipkin-ui:
    image: openzipkin/zipkin-ui
    container_name: zipkin-ui
    environment:
      - ZIPKIN_BASE_URL=http://zipkin:9411
    ports:
      - 80:80
    depends_on:
      - zipkin

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yaml

  otel-collector:
    image: otel/opentelemetry-collector
    container_name: otel-collector
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "8888:8888"
      - "8889:8889"
      - "4317:4317"
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml

  go-gateway:
    build: 
      context: gateway
      dockerfile: Dockerfile.prod
    container_name: go-gateway
    ports:
      - 8080:8080
    environment:
      - APP_ENV=production
    depends_on:
      - zipkin
      - prometheus
      - otel-collector

  go-weather:
    build: 
      context: weather
      dockerfile: Dockerfile.prod
    container_name: go-weather
    ports:
      - 8081:8081
    environment:
      - APP_ENV=production
    depends_on:
      - zipkin
      - prometheus
      - otel-collector