version: '3.8'

services:
  weather:
    build: 
      context: weather
      dockerfile: Dockerfile.prod
    container_name: go-weather
    ports:
      - 8080:8080
    environment:
      - APP_ENV=production