receivers:
  otlp:
    protocols:
      grpc:
  zipkin:

exporters:
  prometheus:
    endpoint: "localhost:8889"
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin]
